ransack_search_example/config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  resources :products, only: [:index] do
    collection do
      get :search
    end
  end
end

ransack_search_example/app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id            :integer          not null, primary key
#  code          :string(10)       not null              # 商品コード
#  name          :string(50)       not null              # 商品名
#  name_kana     :string(50)       default(""), not null # 商品名カナ
#  price         :integer          not null              # 商品価格
#  purchase_cost :integer          not null              # 仕入原価
#  availability  :boolean          not null              # 販売可能フラグ
#  created_at    :datetime
#  updated_at    :datetime
#

class Product < ActiveRecord::Base
end

ransack_search_example/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ransack_search_example/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @q = Product.search
  end

  def search
    @q = Product.search(search_params)
    @products = @q
      .result
      .order(availability: :desc, code: :asc)
      .decorate
  end

  private

  def search_params
    search_conditions = %i(
      code_cont name_cont name_kana_cont availability_true
      price_gteq price_lteq purchase_cost_gteq purchase_cost_lteq
    )
    params.require(:q).permit(search_conditions)
  end
end

ransack_search_example/app/helpers/application_helper.rb
module ApplicationHelper
end

ransack_search_example/app/helpers/simple_search_form_helper.rb
module SimpleSearchFormHelper
end

ransack_search_example/app/helpers/tops_helper.rb
module TopsHelper
end

ransack_search_example/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FormExample" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="">Railsアプリケーション構築ガイド</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
              <%= render 'shared/topnav_link' %>
            </ul>
          </div>
      </div>
    </div>

    <div class="container">
      <% if content_for?(:title) %><h1><%= yield :title %></h1><% end %>
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <hr />

      <footer>
        <p>&copy; Railsアプリケーション構築ガイド 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

ransack_search_example/app/views/products/_search_form.html.erb
<%= render layout: 'shared/search_box' do %>

<div class="row">
<div class="col-sm-6">
  <div class="form-group">
    <label class="col-sm-4 control-label" for="">商品コード</label>
    <div class="col-sm-8">
      <%= f.text_field :code_cont, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-4 control-label" for="">商品名</label>
    <div class="col-sm-8">
      <%= f.text_field :name_cont, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-4 control-label" for="">商品名カナ</label>
    <div class="col-sm-8">
      <%= f.text_field :name_kana_cont, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-4 control-label" for=""></label>
    <div class="col-sm-6">
      <div class="checkbox">
        <label>
          <%= f.check_box :availability_true %>
          販売中のみ
        </label>
      </div>
    </div>
  </div>
</div>

<div class="col-sm-6">
  <div class="form-group">
    <label class="col-sm-4 control-label" for="">最低商品価格</label>
    <div class="col-sm-8">
      <%= f.text_field :price_gteq, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-4 control-label" for="">最高商品価格</label>
    <div class="col-sm-8">
      <%= f.text_field :price_lteq, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-4 control-label" for="">最低仕入原価</label>
    <div class="col-sm-8">
      <%= f.text_field :purchase_cost_gteq, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-4 control-label" for="">最高仕入原価</label>
    <div class="col-sm-8">
      <%= f.text_field :purchase_cost_lteq, class: 'form-control' %>
    </div>
  </div>
</div>

<div class="col-sm-12 row text-center">
  <%= link_to products_path, class: 'btn btn-default btn-left' do %>クリア<% end %>
  <button class="btn btn-default btn-primary" type="submit"><i class="fa fa-search"></i> 検索</button>
</div>

</div>

<% end %>

ransack_search_example/app/views/products/index.html.erb
<% content_for(:title) do %>
  商品検索
<% end %>

<%= search_form_for(@q, url: search_products_path, html: { method: :get, class: 'form-horizontal', role: 'form' }) do |f| %>
  <%= render 'search_form', f: f %>
<% end %>

ransack_search_example/app/views/products/search.html.erb
<% content_for(:title) do %>
  商品検索
<% end %>

<%= search_form_for(@q, url: search_products_path, html: { method: :get, class: 'form-horizontal', role: 'form' }) do |f| %>
  <%= render 'search_form', f: f %>
<% end %>

<%= render layout: 'shared/search_result_box' do %>
  <table class="table table-list ">
  <thead>
    <tr>
      <th>販売状況</th>
      <th>商品コード</th>
      <th>商品名</th>
      <th>販売価格</th>
      <th>仕入原価</th>
    </tr>
  </thead>
  <% @products.each do |product| %>
  <tbody>
  <tr>
    <td><%= product.sales_condition %> </td>
    <td><%= product.code %></td>
    <td><%= product.name %></td>
    <td><%= product.display_price %></td>
    <td><%= product.display_purchase_cost %></td>
  </tr>
  </tbody>
<% end %>
</table>
<% end %>

ransack_search_example/app/views/shared/_search_box.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><i class="fa fa-search"></i> 検索条件</h3>
  </div>
  <div class="panel-body">
    <%= yield %>
  </div>
</div>

ransack_search_example/app/views/shared/_search_result_box.html.erb
<h1>検索結果</h1>
<%= yield %>